d /var/lib/gizmo 0775 gizmo gizmo -
d /run/gizmo 0775 gizmo gizmo -
f /var/lib/gizmo/adc.csv 0664 root gizmo -
C /var/lib/gizmo/setThreshold.env 0664 gizmo gizmo - /usr/share/gizmo/default-state/setThreshold.env
C /var/lib/gizmo/setRunInterval.env 0664 gizmo gizmo - /usr/share/gizmo/default-state/setRunInterval.env
C /var/lib/gizmo/ZMonArg1.env 0664 gizmo gizmo - /usr/share/gizmo/default-state/ZMonArg1.env
C /var/lib/gizmo/ZMonArg2.env 0664 gizmo gizmo - /usr/share/gizmo/default-state/ZMonArg2.env
C /var/lib/gizmo/ZMonArg3.env 0664 gizmo gizmo - /usr/share/gizmo/default-state/ZMonArg3.env
C /var/lib/gizmo/resistance.env 0664 gizmo gizmo - /usr/share/gizmo/default-state/resistance.env
C /var/lib/gizmo/capacitance.env 0664 gizmo gizmo - /usr/share/gizmo/default-state/capacitance.env
C /var/lib/gizmo/normalizeMagFlag.env 0664 gizmo gizmo - /usr/share/gizmo/default-state/normalizeMagFlag.env
C /var/lib/gizmo/latchState.env 0664 gizmo gizmo - /usr/share/gizmo/default-state/latchState.env
C /var/lib/gizmo/Rcalibration.csv 0664 root gizmo - /usr/share/gizmo/default-state/Rcalibration.csv
C /var/lib/gizmo/Rcalibration_ph.csv 0664 root gizmo - /usr/share/gizmo/default-state/Rcalibration_ph.csv
C /var/lib/gizmo/Ccalibration.csv 0664 root gizmo - /usr/share/gizmo/default-state/Ccalibration.csv
C /var/lib/gizmo/Ccalibration_ph.csv 0664 root gizmo - /usr/share/gizmo/default-state/Ccalibration_ph.csv
